package github

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// BuildPRTitle extracts the title from a spec file (first # header).
func BuildPRTitle(specContent string) string {
	lines := strings.Split(specContent, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "# ") {
			return strings.TrimPrefix(line, "# ")
		}
	}
	return "Untitled"
}

// BuildPRBody generates a PR description from spec content and commit info.
func BuildPRBody(specContent string, commits []string, taskID string) string {
	var body strings.Builder

	// Extract summary
	summary := extractSummary(specContent)
	body.WriteString("## Summary\n\n")
	body.WriteString(summary)
	body.WriteString("\n\n")

	// Extract acceptance criteria
	acs := extractAcceptanceCriteria(specContent)
	if len(acs) > 0 {
		body.WriteString("## Acceptance Criteria\n\n")
		for _, ac := range acs {
			body.WriteString(fmt.Sprintf("- [ ] %s\n", ac))
		}
		body.WriteString("\n")
	}

	// List commits
	if len(commits) > 0 {
		body.WriteString("## Commits\n\n")
		for _, commit := range commits {
			body.WriteString(fmt.Sprintf("- %s\n", commit))
		}
		body.WriteString("\n")
	}

	// Footer
	body.WriteString(fmt.Sprintf("---\n\nGenerated by agentic-agent (task: %s)\n", taskID))
	return body.String()
}

// ExtractPRNumber extracts the PR number from a GitHub PR URL.
// Example: "https://github.com/owner/repo/pull/123" → 123
func ExtractPRNumber(url string) (int, error) {
	re := regexp.MustCompile(`/pull/(\d+)`)
	matches := re.FindStringSubmatch(url)
	if len(matches) < 2 {
		return 0, fmt.Errorf("invalid PR URL: %s", url)
	}

	num, err := strconv.Atoi(matches[1])
	if err != nil {
		return 0, fmt.Errorf("failed to parse PR number: %w", err)
	}

	return num, nil
}

// extractSummary extracts the summary section from a spec.
// Looks for "## Summary" or returns first paragraph.
func extractSummary(specContent string) string {
	sections := strings.Split(specContent, "##")
	if len(sections) > 1 {
		for _, section := range sections[1:] {
			if strings.Contains(section, "Summary") {
				// Extract content after "Summary" line
				lines := strings.Split(section, "\n")
				var summary []string
				for i := 1; i < len(lines); i++ {
					line := strings.TrimSpace(lines[i])
					if line == "" || strings.HasPrefix(line, "#") {
						break
					}
					if line != "" {
						summary = append(summary, line)
					}
				}
				return strings.Join(summary, "\n")
			}
		}
	}

	// Fallback: return first non-empty, non-header line
	lines := strings.Split(specContent, "\n")
	for _, line := range lines {
		if strings.TrimSpace(line) != "" && !strings.HasPrefix(line, "#") {
			return line
		}
	}

	return "No summary available"
}

// extractAcceptanceCriteria extracts acceptance criteria from spec.
// Looks for "## Acceptance Criteria" section with list items.
func extractAcceptanceCriteria(specContent string) []string {
	var acs []string
	inACSection := false

	lines := strings.Split(specContent, "\n")
	for _, line := range lines {
		// Check for section header
		if strings.Contains(line, "Acceptance Criteria") && strings.HasPrefix(line, "#") {
			inACSection = true
			continue
		}

		// End AC section if we hit another header
		if inACSection && strings.HasPrefix(line, "#") {
			break
		}

		// Extract list items (starting with "- ")
		if inACSection && strings.HasPrefix(line, "- ") {
			// Remove "- " prefix and checkbox markers
			ac := strings.TrimPrefix(line, "- ")
			ac = strings.TrimPrefix(ac, "[ ] ")
			ac = strings.TrimPrefix(ac, "[x] ")
			ac = strings.TrimSpace(ac)
			if ac != "" {
				acs = append(acs, ac)
			}
		}
	}

	return acs
}
